---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
require(ldccr)
```

# ldccr

<!-- badges: start -->
<!-- badges: end -->

> Various Japanese Corpus Parser

## Installation

``` r
remotes::install_github("paithiov909/ldccr")
```

## Supported Corpus

| ... | Name | License | Link |
| --- | ---- | ------- | ---- |
| 1 | Live Door News Corpus | [CC BY-ND 2.1 JP](http://creativecommons.org/licenses/by-nd/2.1/jp/) | [#](http://www.rondhuit.com/download.html#ldcc) |
| 2 | Japanese Realistic Textual Entailment Corpus | [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) | [#](https://github.com/megagonlabs/jrte-corpus) |



## Download text file from Aozora Bunko

```{r aozora_example}
if (!dir.exists("cache")) dir.create("cache")

text <- ldccr::AozoraBunkoSnapshot %>%
  dplyr::sample_n(1L) %>%
  dplyr::pull("テキストファイルURL") %>%
  ldccr::read_aozora(directory = "cache") %>%
  readr::read_lines()

dplyr::glimpse(text)
```

## License

MIT license.

