# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
#' @keywords internal
read_srt_impl <- function(fileName, collapse = "\n") {
    .Call(`_ldccr_read_srt_impl`, fileName, collapse)
}

#' @noRd
#' @keywords internal
is_uncensored_impl <- function(x, dict) {
    .Call(`_ldccr_is_uncensored_impl`, x, dict)
}

