# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_srt_impl <- function(fileName, collapse = "\n") {
    .Call('_ldccr_read_srt_impl', PACKAGE = 'ldccr', fileName, collapse)
}

