# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Encode and decode 'Sqids'
#'
#' @param numbers A list of integers.
#' @param salt An integer vector.
#' @param ids A character vector.
#' @returns
#' For `sqids_encode()`, a list of integers.
#' For `sqids_decode()`, a character vector.
#' @rdname sqids_impl
#' @keywords internal
sqids_encode <- function(numbers, salt) {
    .Call(`_ldccr_sqids_encode`, numbers, salt)
}

#' @rdname sqids_impl
#' @keywords internal
sqids_decode <- function(ids) {
    .Call(`_ldccr_sqids_decode`, ids)
}

